repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.7
        args: [--line-length=127]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [-e, "git+git://github.com/pycqa/pyflakes.git@1911c20#egg=pyflakes"]
        args: [--extend-ignore=F401,F841]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        additional_dependencies: [torch, tokenize-rt==3.2.0]
        args: [--no-strict-optional, --ignore-missing-imports]
        exclude: setup.py

  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
        args: ["--profile", "black", --line-length=127]
        files: 'blind_walking/.*'
      - id: isort
        args: ["--profile", "black", --line-length=127]
        files: 'tests/.*'
        