repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3.8
        args: ["blind_walking", --line-length=127]
        
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
        args: ["--profile", "black", --line-length=127]
        files: 'blind_walking/.*'
      - id: isort
        args: ["--profile", "black", --line-length=127]
        files: 'tests/.*'
        
