# Dockerfile to build custom image for rl-stablebaseline3 with nvidia ubuntu 20.04 image

# No dgx acc, cant see pybullet simulation
# FROM nvcr.io/nvidia/pytorch:21.08-py3

FROM nvidia/cuda:11.4.2-base-ubuntu20.04

# allow nvidia container toolkit
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics,compute,utility,display
ARG DEBIAN_FRONTEND=noninteractive

# Install packages
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -q -y --no-install-recommends \
    sudo \
    swig \
    cmake \
    ffmpeg 

# Additional stuffs
# atari fix: https://www.codeleading.com/article/25465295172/
RUN apt-get install -q -y --no-install-recommends \
    mesa-utils \
    python3-pip \
    curl \
    wget \
    mesa-utils \
    gcc \
    g++ \
    build-essential \
    libz-dev \
    git

# Force Install of missing dependencies
RUN apt-get -y -f install

# Install sublime
RUN apt-get install -y software-properties-common apt-transport-https
RUN wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
RUN echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
RUN apt-get update && apt-get install -y sublime-text

# Install terminator
RUN apt-get install -y terminator

# copy files to container
COPY . /root/rl-baselines3-zoo-rl_walking_v1.1.0

# install venv
RUN apt-get install -y python3.8 python3.8-dev python3-venv python3.8-venv
RUN python3.8 -m venv /root/py3-8
RUN . /root/py3-8/bin/activate && \
    pip3 install -U pip && \
    pip3 install wheel &&  \
    python3 -m pip install -e /root/rl-baselines3-zoo-rl_walking_v1.1.0/. --ignore-installed
RUN echo "source /root/py3-8/bin/activate" >> /root/.bashrc 

ENTRYPOINT [ "/bin/bash", "-l", "-c" ]
CMD ["bash"]
SHELL ["/bin/bash", "-c"]
CMD /bin/bash -c "source ~/.bashrc""