# Dockerfile to build custom image for rl-stablebaseline3 in DGX

FROM nvcr.io/nvidia/pytorch:21.08-py3

# Install packages
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -q -y --no-install-recommends \
    sudo \
    swig \
    cmake \
    ffmpeg 

# Force Install of missing dependencies
RUN apt-get -y -f install

# copy files to container
COPY . /root/rl-baselines3-zoo-rl_walking_v1.1.0
RUN cd /root/rl-baselines3-zoo-rl_walking_v1.1.0 && python3 -m pip install -e . --ignore-installed

ENTRYPOINT [ "/bin/bash", "-l", "-c" ]
CMD ["bash"]